export type ArticleStatus = "draft" | "published" | "archived"

/**
 * The cover as the backend exposes it — a projection, not the raw Image row.
 * localPath/publicId/tries/lastError are worker internals and never sent
 * (article spec §2.3a/§4.3). `status` is kept because the polling below and the
 * storefront both depend on it.
 */
export interface ArticleCoverImage {
  id: string
  url: string
  status: "pending" | "processing" | "uploaded" | "failed"
  alt: string | null
}

export interface ArticleSeo {
  id: string
  articleId: string
  metaTitle: string | null
  metaDescription: string | null
  metaKeywords: string[]
  canonicalUrl: string | null
  focusKeyword: string | null
  ogTitle: string | null
  ogDescription: string | null
  twitterCard: "summary" | "summary_large_image" | "app" | "player"
  noIndex: boolean
  noFollow: boolean
}

export interface Article {
  id: string
  title: string
  /** Generated by the backend from the title — read-only here (spec §2.10). */
  slug: string
  /** Absent from list responses, which omit it to avoid shipping full bodies (spec §4.3a). */
  content?: string
  authorName: string | null
  tags: string[]
  status: ArticleStatus
  publishedAt: string | null
  viewCount: number
  coverImage: ArticleCoverImage | null
  seo?: ArticleSeo | null
  createdAt: string
  updatedAt: string
}

/** No `slug` and no `excerpt`: the backend generates one and dropped the other. */
export interface CreateArticleInput {
  title: string
  content: string
  authorName?: string
  tags?: string[]
  status?: ArticleStatus
  publishedAt?: string
}

export type UpdateArticleInput = Partial<CreateArticleInput>

export interface UpsertArticleSeoInput {
  metaTitle?: string
  metaDescription?: string
  metaKeywords?: string[]
  canonicalUrl?: string
  focusKeyword?: string
  ogTitle?: string
  ogDescription?: string
  noIndex?: boolean
  noFollow?: boolean
}
