export type ArticleStatus = "draft" | "published" | "archived"

/**
 * The cover as the backend exposes it — a projection of the Image row, not the
 * row itself. Worker bookkeeping (localPath/publicId/tries/lastError) is never
 * sent (backend article spec §2.3a).
 */
export interface ArticleCoverImage {
  id: string
  url: string
  status: "pending" | "processing" | "uploaded" | "failed"
  alt: string | null
}

export interface ArticleSeo {
  metaTitle: string | null
  metaDescription: string | null
  metaKeywords: string[]
  canonicalUrl: string | null
  ogTitle: string | null
  ogDescription: string | null
  twitterCard: "summary" | "summary_large_image" | "app" | "player"
  noIndex: boolean
  noFollow: boolean
}

export interface Article {
  id: string
  title: string
  /** Generated by the backend from the title; stable once published. */
  slug: string
  /**
   * Absent from list responses — the backend omits the Markdown body there so
   * a listing doesn't ship full articles to render card text (spec §4.3a).
   * Only present on the by-slug detail read.
   */
  content?: string
  authorName: string | null
  tags: string[]
  status: ArticleStatus
  /** Null on drafts; this is the date rendered on the card, not createdAt. */
  publishedAt: string | null
  viewCount: number
  /** Always present as a key; null until the worker finishes the upload. */
  coverImage: ArticleCoverImage | null
  seo?: ArticleSeo | null
  createdAt: string
  updatedAt: string
}
